### ISSUE TITLE
Video blank out during video end after compression 🚨

### ISSUE THREAD

**Issue by Ayyarappan** [T2Je/FYVideoCompressor#10]
Thanks for the library support. It meets my requirements and i love used it in my project @T2Je 

But facing issue in Compressed Video blanks during end time. Integrates FYVideoCompressor using podfile. Not updates video bitrate / audio configuration. Used default configuration with quality as medium.

Irrespective of video size and quality, it happens for all video after successfull compression. Depends on video total duration, video blanks at end time. 🚨

************** Video info **************
video codec type: avc1
🔊 **Audio**
ORINGIAL:
bitrate: 317355.66
sampleRate: 48000.0
channels: 2
formatID: 1633772320
TARGET:
bitrate: 128000.0
sampleRate: 44100
formatID: 1633772320
🎬 **Video** 
ORIGINAL:
video size: 261.68463706970215M
bitrate: 3.6022064e+07 b/s
fps: 29.97003
scale size: (1080.0, 1920.0)
TARGET:
video bitrate: 2500000.0 b/s
fps: 24.0
scale size: ((480.0, 853.0))
****************************************

******** Compression finished ✅**********
Compressed video:
time: 5.500333070755005
size: 15.457212448120117M
****************************************

`func compressVideo(sourceUrl:URL?) {
        guard let sourceURL = sourceUrl else {return}
        FYVideoCompressor().compressVideo(sourceURL, quality: .mediumQuality) { result in
            switch result {
            case .success(let compressedVideoURL):
                print("compressedVideoURL: \(compressedVideoURL)")
            case .failure(let error):
                print("error compression: \(error.localizedDescription)")
            }
        }
    }`

 
Please find below attachment for reference. I tried compression on different videos of same size, but this issue repeats in all video compression files. Speedy solution needed @T2Je 

Thanks for your attention.

https://github.com/T2Je/FYVideoCompressor/assets/71223786/4eed6688-05c2-4e99-8b4a-47043977d8f4

**Comment by tsekh01** [comment]
There is a bug in the `struct ReduceFrameEvenlySpaced: VideoFrameReducer` which causes blank out at the end of a video. You can use another reducer `ReduceFrameRandomly` to fix this issue.
`FYVideoCompressor().compressVideo(yourVideoPath, quality: .lowQuality, frameReducer: ReduceFrameRandomly())`

I made a [fork](https://github.com/tsekh01/FYVideoCompressor) to fix this bug. You can have a look.

**Comment by Ayyarappan** [comment]
Hi @T2Je 
Yes, thanks for your speedy solution.

After changing the `VideoFrameReducer` to `ReduceFrameRandomly` fixed the issue 🎉 👍
