### ISSUE TITLE
Crashed when compressing two videos

### ISSUE THREAD

**Issue by fakerlogic** [T2Je/FYVideoCompressor#2]
error msg: 
```
[AVAssetReaderTrackOutput copyNextSampleBuffer] cannot copy next sample buffer before adding this output to an instance of AVAssetReader (using -addOutput:) and calling -startReading on that asset reader"
```

**Comment by petrkahanek** [comment]
Hello, 

I am experiencing crashes when doing batch compression as well.

Error message:
`Thread 26: "*** -[AVAssetReaderTrackOutput copyNextSampleBuffer] cannot copy next sample buffer before adding this output to an instance of AVAssetReader (using -addOutput:) and calling -startReading on that asset reader"`

Any workaround or should wait for bug fix?

**Comment by T2Je** [comment]
Hi,
Sorry to hear that, but I’ve been very busy lately, I &nbsp;will work on it as soon as possible, maybe from next week. Thanks for your email.
-T2Je


------------------ Original ------------------
From: Petr Kahánek ***@***.***&gt;
Date: 周一,6月 6,2022 8:37 下午
To: T2Je/FYVideoCompressor ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [T2Je/FYVideoCompressor] Crashed when compressing two videos(Issue #2)





 
Hello,
 
I am experiencing crashes when doing batch compression as well.
 
Error message:
 Thread 26: "*** -[AVAssetReaderTrackOutput copyNextSampleBuffer] cannot copy next sample buffer before adding this output to an instance of AVAssetReader (using -addOutput:) and calling -startReading on that asset reader"
 
Any workaround or should wait for bug fix?

**Comment by T2Je** [comment]
I'd like to know whether batch compression is concurrency compression or a for-loop compression

**Comment by petrkahanek** [comment]
I was doing for-loop compression.

S pozdravem / Best Regards
Petr Kahánek

On June 17, 2022, "dependabot[bot]" ***@***.***> wrote:
> I'd like to know whether batch compression is concurrency compression
> or a for-loop compression
>

—
Reply to this email directly, view it on GitHub
<https://github.com/T2Je/FYVideoCompressor/issues/2#issuecomment-
1158730943>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AO3IG6DIVJ6U2PCRYE3FISDVPRGY7ANCNFSM5WVEQGKA>.
You are receiving this because you commented.Message ID:
***@***.***>

**Comment by T2Je** [comment]
It seems like we should use different instances of AVAssetReader to do batch compression. I removed the `shared` singleton property and opened the access of the init method. I will merge the #[bug/batchCompression](https://github.com/T2Je/FYVideoCompressor/tree/bug/batchCompression) branch into the main branch later.

**Comment by T2Je** [comment]
#[bug/batchCompression](https://github.com/T2Je/FYVideoCompressor/tree/bug/batchCompression) branch has been merged into the main branch.
